Feature/add fuctionality to add solutions
kochch1337/Capstone-Project pull request #15
Opened 2022-11-28 10:10 UTC by kochch1337

Functionality to add new solutions implemented
add basic styling

2022-11-28 14:14 UTC, JessicaLoers requested changes

2022-11-28 17:49 UTC, kochch1337 commented on components/Button/Button.styled.js
> +import styled, { css, ThemeProvider } from "styled-components";
removed

2022-11-28 17:49 UTC, kochch1337 commented on components/Button/Button.styled.js
> +  }
That's correct but I will also need a Desktop Version where it will be nice and the mobile should not be effected by this.

2022-11-28 17:49 UTC, kochch1337 commented on components/Card/Card.styled.js
> +
removed

2022-11-28 17:49 UTC, kochch1337 commented on components/Card/Card.styled.js
> +import styled, { ThemeProvider } from "styled-components";
removed

2022-11-28 17:50 UTC, kochch1337 commented on components/NavFooter/index.js
> +        </StyledNavigationList>
I'm waiting for a solution for the active attribute and then we will change that

2022-11-28 17:50 UTC, kochch1337 commented on components/SelectPerson/index.js
> +  setPersonId,
changed

2022-11-28 17:50 UTC, kochch1337 commented on pages/Create.js
> +function AppendCard(cardsState, setCardsState, question, answer, tags) {
removed

2022-11-28 17:51 UTC, kochch1337 commented on components/SolutionChanger/index.js
> +import { StyledHeader } from "../Card/Card.styled";
updated as requested

2022-11-30 09:07 UTC, JessicaLoers approved these changes
**You have made it 🏋️‍♀️**

2022-11-30 11:12 UTC, merged